return {
  {
    "nvim-treesitter/nvim-treesitter",
    dependencies = {
      "nvim-treesitter/nvim-treesitter-textobjects",
    },
    branch = "master",
    lazy = false,
    build = ":TSUpdate",
    config = function()
      require("nvim-treesitter.configs").setup {
        ensure_installed = {
          "bash",
          "css",
          "csv",
          "cue",
          "diff",
          "dot",
          "embedded_template",
          "git_config",
          "git_rebase",
          "gitattributes",
          "gitcommit",
          "gitignore",
          "gnuplot",
          "go",
          "gomod",
          "gosum",
          "gotmpl",
          "gowork",
          "graphql",
          "groovy",
          "hcl",
          "helm",
          "hjson",
          "html",
          "http",
          "ini",
          "java",
          "javascript",
          "jq",
          "jsdoc",
          "json",
          "kotlin",
          "lua",
          "make",
          "markdown",
          "markdown_inline",
          "mermaid",
          "nix",
          "pem",
          "proto",
          "python",
          "regex",
          "rego",
          "ruby",
          "rust",
          "sql",
          "terraform",
          "toml",
          "tsv",
          "typescript",
          "vim",
          "vimdoc",
          "vue",
          "xml",
          "yaml",
        },
        auto_install = true,
        highlight = {
          enable = true,
        },

        textobjects = {
          swap = {
            enable = true,
            swap_next = {
              ["<leader>a"] = "@parameter.inner",
            },
            swap_previous = {
              ["<leader>A"] = "@parameter.inner",
            },
          },
        },
      }
    end,
  },
}
