#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse off

yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 9 --label nine

yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_topmost off

yabai -m config auto_balance off

## Change how yabai looks

yabai -m config window_border on
yabai -m config active_window_border_color 0xff3fe25a
yabai -m config window_border_width 6
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 0.90
yabai -m config mouse_drop_action swap
yabai -m config layout bsp
yabai -m config top_padding 2
yabai -m config bottom_padding 2
yabai -m config left_padding 5
yabai -m config right_padding 5
yabai -m config window_gap 5
