require 'user.core'
require 'user.plugins'
require 'user.statuscol'
require 'user.lualine'
require 'user.colorscheme'
require 'user.keymap'
require 'user.cmp'
require 'user.lsp'
require 'user.copilot'
require 'user.treesitter'
-- require 'user.ale'
require 'user.nvim-lint'
require 'user.select_ease'
require 'user.debugger'
require 'user.toggleterm'
require 'user.comment'
require 'user.filetype'
require 'user.devicons'
require 'user.jabs'
require 'user.images'
require 'user.projections'
require 'user.oil'
require 'user.treesj'
-- require 'user.aerial'
-- require 'user.nvim-window-mode'
-- require 'user.winbar'
--require 'user.autoclose'
require 'user.overrides'
