require 'user.core'
require 'user.plugins'
require 'user.colorscheme'
require 'user.keymap'
require 'user.cmp'
require 'user.lsp'
require 'user.treesitter'
require 'user.debugger'
require 'user.toggleterm'
require 'user.filetype'
require 'user.devicons'
require 'user.jabs'
require 'user.feline'
require 'user.images'
-- require 'user.winbar'
require 'user.autoclose'
require 'user.overrides'
